More tests and proptests
keep-starknet-strange/shenlong pull request #54
Opened 2023-02-28 15:06 UTC by edg-l

Adds tests and proptests for the binary operations

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

2023-02-28 19:00 UTC, edg-l commented
This reworks the way type id and names are stored (imho easier now), so that it works better with the debug code.

I also changed the return type from always being a struct to being only a struct if the function returns more than 1 value.

I need to fix a couple bugs (2 tests don't pass) and will be ready

2023-03-01 12:12 UTC, LucasLvy requested changes
How about having only 1 template where the operation is also set in the context ?

2023-03-01 12:12 UTC, LucasLvy commented on core/tests/proptests.rs
> +    expected += if expected < zero { two } else { zero };
```suggestion
    let two = BigInt::from(2).pow(x.bits() as u32);
    expected = expected.modpow(&BigInt::from(1), &two);
```

2023-03-01 12:23 UTC, LucasLvy approved these changes
lgtm

2023-03-01 12:25 UTC, merged